spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update

server:
  forward-headers-strategy: framework

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /api/health-check
  endpoint:
    health:
      enabled: true

logging:
  level:
    root: error
    org.springframework.security: error

cors-allowed-origins:
  https://bbogak.com,
  https://www.bbogak.com,
  https://dev.bbogak.com,
  https://web-dev.bbogak.com