spring:
  profiles:
    active: local
    group:
      test: "test"
      local: "local, datasource"
      dev: "dev, datasource"
      prod: "prod, datasource"
    include:
      - security
      - swagger
      - aws

logging:
  level:
    root: INFO  # 모든 로그에 대한 기본 로그 레벨 설정
    org.springframework.security: TRACE

scheduler:
  thread:
    pool:
      size: 2

sentry:
  dsn: ${SENTRY_DSN}
  enable-tracing: true
  tracesSampleRate: 1.0
  debug: true
  environment: local
