spring:
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

server:
  forward-headers-strategy: framework
