spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

cors-allowed-origins:
  http://localhost:8080,
  http://localhost:3000,
  http://114.70.23.79:8080,
  http://52.65.6.74:8080,
  http://118.67.129.12,
  https://bbogak.com,
  https://www.bbogak.com,
  https://dev.bbogak.com,
  https://web-dev.bbogak.com


