spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
    org.springframework.security: info

server:
  forward-headers-strategy: framework

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /api/health-check
  endpoint:
    health:
      enabled: true

cors-allowed-origins:
  http://localhost:8080,
  http://localhost:3000,
  http://114.70.23.79:8080,
  http://52.65.6.74:8080,
  http://118.67.129.12,
  https://bbogak.com,
  https://www.bbogak.com,
  https://dev.bbogak.com,
  https://web-dev.bbogak.com
