name: deploy-bbogak-dev-server
on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy spring MainServer(main)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd ~/bbo-gak-server
            git fetch origin main
            git merge origin/main
            ./gradlew clean build
            ./gradlew openapi3
            docker rm bbo-gak-server_back_1 --force
            docker rmi bbo-gak-server_back
            docker-compose -f docker-compose-dev.yml up --build -d
